### ISSUE TITLE
Bro output needs protocol removed

### ISSUE THREAD

**Issue by sethhall** [csirtgadgets/p5-cif-sdk#19]
I think this is something that I'll adjust for on the Bro side as well, but as of the current and upcoming release, Bro does URL matching without the protocol and data fed into the intelligence framework currently needs to have the protocol removed.

I would love feedback on it if you have thoughts too, but my thinking was that I don't necessarily care if someone is looking to match on https://google.com/ or http://google.com/ so what the intel framework needs to take in is just google.com/

**Comment by wesyoung** [comment]
that should be easy enough to handle for.. i don't know that i have an opinion either way (wrt CIF anyway). we do try to be as "specific" as possible when describing something, if only so you can make a more "informed" decision on the other end where data-consumption is taking place...

**Comment by wesyoung** [comment]
also, do you have an example of what a bro urlfeed looks like so i can write a test and double check my work..?

**Comment by wesyoung** [comment]
my test output looks like:

```
#fields	indicator	indicator_type	meta.desc	meta.cif_confidence	meta.source
google.com	Intel::URL	zeus|botnet	50	me.com
google.com/1234.htm	Intel::URL	zeus|botnet	50	me.com
google.com/1234.htm	Intel::URL	zeus|botnet	50	me.com
192.168.1.1	Intel::ADDR	zeus|botnet	50	me.com1..4
```

**Comment by sethhall** [comment]
Yeah, that should be fine as long as all of that whitespace is literal tabs (even after #fields).  We support a few extra CIF fields too.

```
redef record Intel::MetaData += {
	## Maps to the Impact field in the Collective Intelligence Framework.
	cif_impact:     string &optional;
	## Maps to the Severity field in the Collective Intelligence Framework.
	cif_severity:   string &optional;
	## Maps to the Confidence field in the Collective Intelligence Framework.
	cif_confidence: double &optional;
};
```
