### ISSUE TITLE
Need Snort output for p5-cif-sdk

### ISSUE THREAD

**Issue by JesseBowling** [csirtgadgets/p5-cif-sdk#23]
Need Snort rule output for python SDK similar to https://github.com/csirtgadgets/p5-cif-sdk/blob/master/lib/CIF/SDK/Format/Snort.pm

Should probably support both open source Snort as well as Sourcefire rule formats

**Comment by wesyoung** [comment]
so why not log this in https://github.com/csirtgadgets/py-cifsdk/issues ?

**Comment by JesseBowling** [comment]
Because I was in the wrong repo when I logged this and thought I already was logging it there. Damnit.

**Comment by wesyoung** [comment]
hehe. i'm just messing with ya.. i'm logging them now :)

**Comment by wesyoung** [comment]
https://github.com/csirtgadgets/py-cifsdk/issues/1
