### ISSUE TITLE
Failed to upconvert metadata to 1.1. Errors:

### ISSUE THREAD

**Issue by jgedeon120** [csirtgadgets/p5-cif-sdk#26]
On Ubuntu 14.04.2 LTS, following the install instructions the following is given.

Failed to upconvert metadata to 1.1. Errors:
Missing mandatory field, 'version' (version) [Validation: 1.0]
 at /loader/0x1fb0ea8/App/cpanminus/script.pm line 1.

**Comment by wesyoung** [comment]
do you still get this with the current master?

**Comment by jgedeon120** [comment]
Wes,

I will check again this weekend.

Joe

On Fri, May 22, 2015 at 7:57 AM, Wes <notifications@github.com> wrote:

> do you still get this with the current master?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/csirtgadgets/p5-cif-sdk/issues/26#issuecomment-104643125>
> .
>



-- 
Registered Linux User # 379282

**Comment by jgedeon120** [comment]
Sorry for the delay.  Just tested the install from a fresh updated version of Ubuntu 14.04.2 an I still get the same error.

...
Setting up libmodule-install-perl (1.06-1) ...
Processing triggers for libc-bin (2.19-0ubuntu6.6) ...
joe@cifv2-agent:~$ sudo cpanm http://backpan.perl.org/authors/id/M/MS/MSCHILLI/Log-Log4perl-1.44.tar.gz
--> Working on http://backpan.perl.org/authors/id/M/MS/MSCHILLI/Log-Log4perl-1.44.tar.gz
Fetching http://backpan.perl.org/authors/id/M/MS/MSCHILLI/Log-Log4perl-1.44.tar.gz ... OK
Configuring Log-Log4perl-1.44 ... OK
Building and testing Log-Log4perl-1.44 ... OK
Successfully installed Log-Log4perl-1.44
1 distribution installed
joe@cifv2-agent:~$ sudo cpanm git://github.com/csirtgadgets/p5-cif-sdk.git
Cloning git://github.com/csirtgadgets/p5-cif-sdk.git ... OK
--> Working on git://github.com/csirtgadgets/p5-cif-sdk.git
Configuring /tmp/Z0GDvaqZZL ... OK
Failed to upconvert metadata to 1.1. Errors:
Missing mandatory field, 'version' (version) [Validation: 1.0]
 at /loader/0x66ca30/App/cpanminus/script.pm line 1.

**Comment by wesyoung** [comment]
try master again, something screwy with Module::Build, went back to MakeMaker... lmk..

**Comment by jgedeon120** [comment]
Installed as expected.
