### ISSUE TITLE
Add support for additional Bro types (email, hash)

### ISSUE THREAD

**Issue by giovino** [csirtgadgets/p5-cif-sdk#28]
Add support for Bro output observable types: (email, file hash, ?)

https://github.com/csirtgadgets/p5-cif-sdk/blob/master/lib/CIF/SDK/Format/Bro.pm#L15

See this thread for the bug report. 
https://mail.google.com/mail/u/0/?pli=1#inbox/14da1b8b30b926fb

**Comment by wesyoung** [comment]
https://groups.google.com/forum/#!topic/ci-framework/_LpVNUwIkVU

**Comment by wesyoung** [comment]
in theory, this should fix it... 

if `cif --otype hash` isn't working, log it to: https://github.com/csirtgadgets/massive-octo-spice/issues

with an example feed/config (i don't know that i have any offhand) and we can work through it... fake data is OK :)
