### ISSUE TITLE
error with whitelisting IPV6 observable

### ISSUE THREAD

**Issue by giovino** [csirtgadgets/p5-cif-sdk#37]
when adding a IPV6 address with the tag 'whitelist' and then generating a ipv6 feed you get the following error:

```invalid key at /usr/local/share/perl/5.18.2/CIF/SDK/Feed/Ipv6.pm line 33```

which refers to:

```line 33: $whitelist->add_string($_) foreach (@{$args->{'whitelist'}});```

you can see this error in action with the following script:

https://github.com/giovino/massive-octo-spice/blob/develop/contrib/whitelist_testing.sh

**Comment by wesyoung** [comment]
http://cpansearch.perl.org/src/DROLSKY/Data-Validate-IP-0.24/lib/Data/Validate/IP.pm

1. multi cast addresses are OK
2. google addresses are not ok
3. google addresses don't resolve?
4. socket.h functions are coming back with null (maybe cause things are un-routable it's not a valid address)

maybe test with fast, fall back to regex style, bring Net::Patricia local?

**Comment by wesyoung** [comment]
i am. fucking. stupid.
